check static linking

diff --git a/.github/workflows/master_ci.yml b/.github/workflows/master_ci.yml
--- a/.github/workflows/master_ci.yml
+++ b/.github/workflows/master_ci.yml
@@ -69,6 +69,14 @@ jobs:
           cd build
           cmake .. --preset=minimal -DKAHYPAR_CI_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DKAHYPAR_STATIC_LINK_DEPENDENCIES=ON
           make -j2 MtKaHyPar
+          if [[ $(ldd mt-kahypar/application/MtKaHyPar | grep hwloc) ]]; then
+            echo "Error: hwloc is dynamically linked"
+            exit 1
+          fi
+          if [[ $(ldd mt-kahypar/application/MtKaHyPar | grep boost) ]]; then
+            echo "Error: boost is dynamically linked"
+            exit 1
+          fi
 
   mt_kahypar_test_suite:
     name: Test Suite
