Transition to modern cmake (#199)
Transition to modern cmake and remove git submodules. Should make the build system more stable, adds support for static linking, improves and extends the installation targets, allows direct integration of the C library via cmake via find_package/FetchContent.

Note: removes the option for disabling boost.
Because loading a preset also requires boost since #196, we can't
do anything meaningful when boost is disabled. Thus we might as well
remove the option.

diff --git a/.github/workflows/master_ci.yml b/.github/workflows/master_ci.yml
--- a/.github/workflows/master_ci.yml
+++ b/.github/workflows/master_ci.yml
@@ -13,51 +13,72 @@ jobs:
     name: Ubuntu Build
     strategy:
       matrix:
-        compiler: [ { os: ubuntu-20.04, cpp: g++-9, cc: gcc-9, install_cmd: g++-9 gcc-9 },
-                    { os: ubuntu-20.04, cpp: g++-10, cc: gcc-10, install_cmd: g++-10 gcc-10 },
-                    { os: ubuntu-22.04, cpp: g++-11, cc: gcc-11, install_cmd: g++-11 gcc-11 },
-                    { os: ubuntu-22.04, cpp: g++-12, cc: gcc-12, install_cmd: g++-12 gcc-12 },
-                    { os: ubuntu-22.04, cpp: clang++, cc: clang, install_cmd: clang }  ]
+        compiler: [ { os: ubuntu-22.04, cpp: g++-11, cc: gcc-11, install_cmd: g++-11 gcc-11 },
+                    { os: ubuntu-24.04, cpp: g++-14, cc: gcc-14, install_cmd: g++-14 gcc-14 },
+                    { os: ubuntu-24.04, cpp: clang++, cc: clang, install_cmd: clang }  ]
 
     runs-on: ${{ matrix.compiler.os }}
     env:
-      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
       CI_ACTIVE : 1
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 1
+        uses: actions/checkout@v4
 
       - name: Install Dependencies
         run: |
           sudo apt-get install libtbb-dev libboost-program-options-dev libhwloc-dev lcov gcovr ${{ matrix.compiler.install_cmd }}
 
-      - name: Install Mt-KaHyPar Test Suite
+      - name: Install Mt-KaHyPar
         env:
           CC: ${{ matrix.compiler.cc }}
           CXX: ${{ matrix.compiler.cpp }}
         run: |
-          git submodule update --init --recursive
           rm -rf build
           mkdir build
           cd build
-          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
+          cmake .. --preset=default -DKAHYPAR_CI_BUILD=ON
           make -j2 MtKaHyPar
 
-  mt_kahypar_test_suite:
-    name: Test Suite
-    runs-on: ubuntu-20.04
+  mt_kahypar_static_build:
+    name: Statically Linked Build
+    runs-on: ubuntu-24.04
     env:
-      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
       CI_ACTIVE : 1
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-         fetch-depth: 1
+        uses: actions/checkout@v4
+
+      - name: Install Dependencies
+        run: |
+          sudo apt-get install libtbb-dev libboost-program-options-dev libhwloc-dev libudev-dev
+
+      - name: Install Mt-KaHyPar
+        run: |
+          rm -rf build
+          mkdir build
+          cd build
+          cmake .. --preset=minimal -DKAHYPAR_CI_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DKAHYPAR_STATIC_LINK_DEPENDENCIES=ON
+          make -j2 MtKaHyPar
+          if [[ $(ldd mt-kahypar/application/MtKaHyPar | grep hwloc) ]]; then
+            echo "Error: hwloc is dynamically linked"
+            exit 1
+          fi
+          if [[ $(ldd mt-kahypar/application/MtKaHyPar | grep boost) ]]; then
+            echo "Error: boost is dynamically linked"
+            exit 1
+          fi
+
+  mt_kahypar_test_suite:
+    name: Test Suite
+    runs-on: ubuntu-22.04  # note: stay on 22.04 since lcov behaves weird on 24.04
+    env:
+      CI_ACTIVE : 1
+
+    steps:
+      - name: Checkout HEAD
+        uses: actions/checkout@v4
 
       - name: Install Dependencies
         run: |
@@ -65,40 +86,36 @@ jobs:
 
       - name: Install Mt-KaHyPar Test Suite
         run: |
-          git submodule update --init --recursive
-          rm -rf debug
-          mkdir debug
-          cd debug
-          cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DKAHYPAR_USE_GCOV=ON -DKAHYPAR_CI_BUILD=ON
-          make -j2 mt_kahypar_tests;
+          rm -rf build
+          mkdir build
+          cd build
+          cmake .. --preset=dev -DCMAKE_BUILD_TYPE=DEBUG -DKAHYPAR_CI_BUILD=ON -DKAHYPAR_USE_GCOV=ON
+          make -j2 mtkahypar_tests
 
       - name: Run Mt-KaHyPar Tests
         run: |
-          cd debug
-          ./tests/mt_kahypar_tests;
+          cd build
+          ./tests/mtkahypar_tests
 
       - name: Report Code Coverage
         run: |
-          cd debug
-          lcov --directory . --capture --output-file coverage.info;
-          lcov --remove coverage.info '/usr/*' --output-file coverage.info;
-          lcov --list coverage.info;
-          gcovr -r ../ -x > report.xml;
+          cd build
+          lcov --directory . --capture --output-file coverage.info --exclude '**/external_tools/**/*' --exclude '**/tests/**/*' --exclude '**/googletest-src/**/*'
+          lcov --remove coverage.info '/usr/**/*' '**/external_tools/**/*' '**/tests/**/*' --output-file coverage.info
+          lcov --list coverage.info
+          gcovr -r ../ -x > report.xml
           cd ..
           bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
 
   mt_kahypar_integration_tests:
     name: Integration Tests
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     env:
-      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
       CI_ACTIVE : 1
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-         fetch-depth: 1
+        uses: actions/checkout@v4
 
       - name: Install Dependencies
         run: |
@@ -106,11 +123,10 @@ jobs:
 
       - name: Install Mt-KaHyPar Integration Tests
         run: |
-          git submodule update --init --recursive
           rm -rf build
           mkdir build
           cd build
-          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
+          cmake .. --preset=python -DKAHYPAR_CI_BUILD=ON
           make -j2 MtKaHyPar
           make -j2 VerifyPartition
           make -j2 GridGraphGenerator
@@ -122,16 +138,13 @@ jobs:
 
   mt_kahypar_c_interface_tests:
     name: C Interface Tests
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     env:
-      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
       CI_ACTIVE : 1
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-         fetch-depth: 1
+        uses: actions/checkout@v4
 
       - name: Install Dependencies
         run: |
@@ -139,25 +152,21 @@ jobs:
 
       - name: Run Mt-KaHyPar C Library Interface Tests
         run: |
-          git submodule update --init --recursive
           rm -rf build
           mkdir build
           cd build
-          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
-          make -j2 interface_test
+          cmake .. --preset=dev -DKAHYPAR_CI_BUILD=ON
+          make -j2 mtkahypar_interface_test
 
   mt_kahypar_python_interface_tests:
     name: Python Interface Tests
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     env:
-      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
       CI_ACTIVE : 1
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-         fetch-depth: 1
+        uses: actions/checkout@v4
 
       - name: Install Dependencies
         run: |
@@ -165,11 +174,10 @@ jobs:
 
       - name: Build Mt-KaHyPar Python Interface
         run: |
-          git submodule update --init --recursive
           rm -rf build
           mkdir build
           cd build
-          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
+          cmake .. --preset=python -DKAHYPAR_CI_BUILD=ON
           make mtkahypar_python -j2
 
       - name: Run Mt-KaHyPar Python Interface Tests
@@ -186,9 +194,7 @@ jobs:
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-         fetch-depth: 1
+        uses: actions/checkout@v4
 
       - name: Setup MSYS2
         uses: msys2/setup-msys2@v2
@@ -204,26 +210,21 @@ jobs:
         run: |
           echo "${{ runner.temp }}/msys64/mingw64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
-      - name: Rename TBB library file
-        run: |
-          Ren ${{ runner.temp }}/msys64/mingw64/lib/libtbb12.dll.a ${{ runner.temp }}/msys64/mingw64/lib/libtbb.dll.a
-
       - name: Install Mt-KaHyPar Multilevel Tests
         shell: msys2 {0}
         run: |
-          git submodule update --init --recursive
           rm -rf build
           mkdir build
           cd build
           export CMAKE_GENERATOR="MSYS Makefiles"
-          /mingw64/bin/cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON -DKAHYPAR_ENABLE_HIGHEST_QUALITY_FEATURES=OFF -DKAHYPAR_ENABLE_LARGE_K_PARTITIONING_FEATURES=OFF
-          make -j2 mt_kahypar_tests
+          /mingw64/bin/cmake .. --preset=dev -DKAHYPAR_CI_BUILD=ON -DKAHYPAR_ENABLE_HIGHEST_QUALITY_FEATURES=OFF -DKAHYPAR_ENABLE_LARGE_K_PARTITIONING_FEATURES=OFF
+          make -j2 mtkahypar_tests
 
       - name: Run Mt-KaHyPar Tests
         shell: msys2 {0}
         run: |
           cd build
-          ./tests/mt_kahypar_tests
+          ./tests/mtkahypar_tests
 
   mt_kahypar_macos_build:
     name: MacOS Build
@@ -233,9 +234,7 @@ jobs:
 
     steps:
       - name: Checkout HEAD
-        uses: actions/checkout@v3
-        with:
-         fetch-depth: 1
+        uses: actions/checkout@v4
 
       - name: Install Dependencies
         run: |
@@ -243,14 +242,13 @@ jobs:
 
       - name: Install Mt-KaHyPar Multilevel Tests
         run: |
-          git submodule update --init --recursive
           rm -rf build
           mkdir build
           cd build
-          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
-          make -j2 mt_kahypar_tests
+          cmake .. --preset=dev -DKAHYPAR_CI_BUILD=ON
+          make -j2 mtkahypar_tests
 
       - name: Run Mt-KaHyPar Tests
         run: |
           cd build
-          ./tests/mt_kahypar_tests
+          ./tests/mtkahypar_tests
